# Generated by Django 4.2.2 on 2023-06-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UrineStrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strip_image", models.ImageField(upload_to="strips/")),
                ("analysis_result", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
